# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainApp.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1219, 665)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonToDo = QtWidgets.QPushButton(self.centralwidget)
        self.buttonToDo.setGeometry(QtCore.QRect(90, 130, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonToDo.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonToDo.setIcon(icon)
        self.buttonToDo.setObjectName("buttonToDo")
        self.buttonLoad_Table = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLoad_Table.setGeometry(QtCore.QRect(90, 170, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonLoad_Table.setFont(font)
        self.buttonLoad_Table.setObjectName("buttonLoad_Table")
        self.buttonScroll_Text = QtWidgets.QPushButton(self.centralwidget)
        self.buttonScroll_Text.setGeometry(QtCore.QRect(90, 210, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonScroll_Text.setFont(font)
        self.buttonScroll_Text.setObjectName("buttonScroll_Text")
        self.buttonDisplay = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDisplay.setGeometry(QtCore.QRect(710, 530, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonDisplay.setFont(font)
        self.buttonDisplay.setObjectName("buttonDisplay")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(670, 260, 231, 161))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.labelContext = QtWidgets.QLabel(self.centralwidget)
        self.labelContext.setGeometry(QtCore.QRect(390, 10, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelContext.setFont(font)
        self.labelContext.setObjectName("labelContext")
        self.buttonDate = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDate.setGeometry(QtCore.QRect(90, 250, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonDate.setFont(font)
        self.buttonDate.setObjectName("buttonDate")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(670, 210, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(670, 440, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(670, 480, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setMaximum(11)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.labelDate = QtWidgets.QLabel(self.centralwidget)
        self.labelDate.setGeometry(QtCore.QRect(270, 250, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDate.setFont(font)
        self.labelDate.setFrameShape(QtWidgets.QFrame.Box)
        self.labelDate.setObjectName("labelDate")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(670, 90, 231, 17))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(670, 130, 231, 17))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.labelToDo = QtWidgets.QLabel(self.centralwidget)
        self.labelToDo.setGeometry(QtCore.QRect(270, 130, 201, 21))
        self.labelToDo.setFrameShape(QtWidgets.QFrame.Box)
        self.labelToDo.setObjectName("labelToDo")
        self.labelTable = QtWidgets.QLabel(self.centralwidget)
        self.labelTable.setGeometry(QtCore.QRect(270, 170, 201, 21))
        self.labelTable.setFrameShape(QtWidgets.QFrame.Box)
        self.labelTable.setObjectName("labelTable")
        self.labelScroll = QtWidgets.QLabel(self.centralwidget)
        self.labelScroll.setGeometry(QtCore.QRect(270, 210, 201, 21))
        self.labelScroll.setFrameShape(QtWidgets.QFrame.Box)
        self.labelScroll.setObjectName("labelScroll")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(670, 170, 231, 22))
        self.comboBox.setObjectName("comboBox")
        self.labelLogo = QtWidgets.QLabel(self.centralwidget)
        self.labelLogo.setGeometry(QtCore.QRect(930, 590, 281, 31))
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap(":/icons/Logo.PNG"))
        self.labelLogo.setObjectName("labelLogo")
        self.buttonCustom = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCustom.setGeometry(QtCore.QRect(90, 290, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonCustom.setFont(font)
        self.buttonCustom.setObjectName("buttonCustom")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1219, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Sroll_Area_Text = QtWidgets.QAction(MainWindow)
        self.actionLoad_Sroll_Area_Text.setObjectName("actionLoad_Sroll_Area_Text")
        self.actionStart_ToDo_List = QtWidgets.QAction(MainWindow)
        self.actionStart_ToDo_List.setObjectName("actionStart_ToDo_List")
        self.actionDisplay_Table_Data = QtWidgets.QAction(MainWindow)
        self.actionDisplay_Table_Data.setEnabled(False)
        self.actionDisplay_Table_Data.setObjectName("actionDisplay_Table_Data")
        self.actionDisplay_Main_Window_Selections = QtWidgets.QAction(MainWindow)
        self.actionDisplay_Main_Window_Selections.setObjectName("actionDisplay_Main_Window_Selections")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPyQt_Demo_Help = QtWidgets.QAction(MainWindow)
        self.actionPyQt_Demo_Help.setObjectName("actionPyQt_Demo_Help")
        self.actionLoad_Table_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Table_Data.setObjectName("actionLoad_Table_Data")
        self.actionHelp_File = QtWidgets.QAction(MainWindow)
        self.actionHelp_File.setObjectName("actionHelp_File")
        self.menuFile.addAction(self.actionLoad_Sroll_Area_Text)
        self.menuFile.addAction(self.actionLoad_Table_Data)
        self.menuRun.addAction(self.actionStart_ToDo_List)
        self.menuRun.addAction(self.actionDisplay_Table_Data)
        self.menuRun.addAction(self.actionDisplay_Main_Window_Selections)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp_File)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonToDo.setText(_translate("MainWindow", "ToDo List"))
        self.buttonLoad_Table.setText(_translate("MainWindow", "Load Table Data"))
        self.buttonScroll_Text.setText(_translate("MainWindow", "Load Scroll Text"))
        self.buttonDisplay.setText(_translate("MainWindow", "Display Selections"))
        self.labelContext.setText(_translate("MainWindow", "Right Click for Context Menus"))
        self.buttonDate.setText(_translate("MainWindow", "Select Date"))
        self.labelDate.setText(_translate("MainWindow", "Date = "))
        self.radioButton.setText(_translate("MainWindow", "Radio Button Selection"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.labelToDo.setText(_translate("MainWindow", "Total ToDos = ?"))
        self.labelTable.setText(_translate("MainWindow", "No Table Data Loaded"))
        self.labelScroll.setText(_translate("MainWindow", "Scroll Data Not Loaded"))
        self.buttonCustom.setText(_translate("MainWindow", "Custom Control"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLoad_Sroll_Area_Text.setText(_translate("MainWindow", "Load Sroll Area Text"))
        self.actionStart_ToDo_List.setText(_translate("MainWindow", "Start ToDo List"))
        self.actionDisplay_Table_Data.setText(_translate("MainWindow", "Display Table Data"))
        self.actionDisplay_Main_Window_Selections.setText(_translate("MainWindow", "Display Main Window Selections"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionPyQt_Demo_Help.setText(_translate("MainWindow", "PyQt% Demo Help"))
        self.actionLoad_Table_Data.setText(_translate("MainWindow", "Load Table Data"))
        self.actionHelp_File.setText(_translate("MainWindow", "Help File"))

import resources_rc
